# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-08-14 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(max_length=2)),
                ('min', models.CharField(max_length=2)),
                ('sec', models.CharField(max_length=2)),
            ],
        ),
    ]
